[book]
authors = ["PuQing"]
language = "en"
src = "src"
title = "gflow Documentation"
description = "A lightweight, single-node job scheduler inspired by Slurm"

[build]
build-dir = "book"
create-missing = false
